### PR TITLE
Classes, CamelCase

### PR DESCRIPTION
**Pull request by regiseduardogregol**
basics :+1:

### CODE REVIEW

**Comment by caarlos0** [comment]
Can you can add something about Single Responsibility Principle? (since you start talking about classes) :beers:

**Comment by regiseduardogregol** [comment]
maybe, or another collaborator can :)

**Comment by luizkowalski** [comment]
I think that SRP can be added in another PR (maybe on a SOLID chapter)...This one looks good to merge

**Comment by caarlos0** [comment]
ok then =D

**Pull request merged**
